<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/category/">Kategorie</a></li>
    <li class="current"><a href="#">Nová kategorie</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Kategorie</span></h2>
    </div><!--contenttitle-->
    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <p>
            <label>Název*</label>
            <span class="field">
                <input class="longinput" type="text" name="title" required value="{echo isset($category)? $category->title: ""}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Rodičovská kategorie</label>
            <span class="field">
                <select class="longinput" name="parent">
                    <option></option>
                    {if !empty($categories)}
                        {foreach $cat in $categories}
                            {if $cat->parentId == 0}
                                <option value="{echo $cat->id}">+ {echo $cat->title}</option>
                            {/if}{else}
                                <option value="{echo $cat->id}">++ {echo $cat->title}</option>
                            {/else}
                        {/foreach}
                    {/if}
                </select>
                {if isset($errors["parentId"])}
                <label class="error">{echo join("<br/>", $errors["parentId"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Pořadí<small>(1-99)</small></label>
            <span class="field">
                <input class="longinput" type="text" pattern="[\d]{0,2}" name="rank" value="{echo isset($category)? $category->rank: ""}" />
                {if isset($errors["rank"])}
                <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Skupinová kategorie</label>
            <span class="field">
                <select name="group">
                    <option value="0">Ne</option>
                    <option value="1">Ano</option>
                </select>
            </span>
        </p>
        <p>
            <label>Prodejné</label>
            <span class="field">
                <select name="selable">
                    <option value="0">Ne</option>
                    <option value="1">Ano</option>
                </select>
            </span>
        </p>
        <p>
            <label>Popis*</label>
            <span class="field">
                <textarea rows="5" required name="text" id="ckeditor">{echo isset($category)? $category->mainText: ""}</textarea>
                {if isset($errors["mainText"])}
                <label class="error">{echo join("<br/>", $errors["mainText"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Název</label>
            <span class="field">
                <input required class="longinput" type="text" name="metaTitle" 
                       value="{echo isset($category)? $category->metaTitle: ""}" />
                {if isset($errors["metaTitle"])}
                <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Klíčová slova</label>
            <span class="field">
                <input required class="longinput" type="text" name="metaKeywords" 
                       value="{echo isset($category)? $category->metaKeywords: ""}" />
                {if isset($errors["metaKeywords"])}
                <label class="error">{echo join("<br/>", $errors["metaKeywords"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Popis</label>
            <span class="field">
                <textarea required class="longinput" rows="5" name="metaDescription">{echo isset($category)? $category->metaDescription: ""}</textarea>
                {if isset($errors["metaDescription"])}
                <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                {/if}
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitAddCategory" type="submit" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>