<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/category/">Category List</a></li>
    <li class="current"><a href="#">Add Category</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Category informations</span></h2>
    </div><!--contenttitle-->
    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <p>
            <label>Title</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo isset($category)? $category->title: ""}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>

        <p>
            <label>Parent Category </label>
            <span class="field">
                <select class="longinput" name="parent">
                    {if !empty($categories)
                    {foreach $cat in $categories}
                    <option value="{echo $cat->getId()}">{echo $cat->getTitle()}</option>
                    {/foreach}
                    {/if}
                </select>
                 {if isset($errors["parentId"])}
                <label class="error">{echo join("<br/>", $errors["parentId"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Rank (0-99)</label>
            <span class="field">
                <input class="longinput" type="number" name="rank" value="{echo isset($category)? $category->rank: ""}" />
                {if isset($errors["rank"])}
                <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Group </label>
            <span class="field">
                <select name="group">
                    <option value="0" selected>no</option>
                    <option value="1">yes</option>
                </select>
            </span>
        </p>
        <p>
            <label>Description</label>
            <span class="field">
                <textarea cols="85" rows="5" name="text" id="ckeditor">{echo isset($category)? $category->mainText: ""}</textarea>
                {if isset($errors["mainText"])}
                <label class="error">{echo join("<br/>", $errors["mainText"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Title</label>
            <span class="field">
                <input class="longinput" type="text" name="metaTitle" value="{echo isset($category)? $category->metaTitle: ""}" />
                {if isset($errors["metaTitle"])}
                <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Keywords</label>
            <span class="field">
                <input class="longinput" type="text" name="metaKeywords" value="{echo isset($category)? $category->metaKeywords: ""}" />
                {if isset($errors["metaKeywords"])}
                <label class="error">{echo join("<br/>", $errors["metaKeywords"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Description</label>
            <span class="field">
                <textarea class="longinput" cols="85" rows="5" name="metaDescription" id="ckeditor">{echo isset($category)? $category->metaDescription: ""}</textarea>
                {if isset($errors["metaDescription"])}
                <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                {/if}
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitAddCategory" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>