<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/category/">Category List</a></li>
    <li><a href="/admin/category/add/">Add Category</a></li>
    <li class="current"><a href="#">Edit Category</a></li>
</ul><!--maintabmenu-->
<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Edit Category</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <p>
            <label>Title</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo $category->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Parent category</label>
            <span class="field">
                <select class="longinput" name="parent">
                    <option></option>   
                    {if !empty($categories)}
                        {foreach $cat in $categories}
                            {script $s = ""}
                            {if $category->getParentId() == $cat->id}
                                {script $s = "selected"}
                            {/if}
                            {if $cat->id != $category->id}
                                <option value="{echo $cat->id}" {echo $s}>{echo $cat->title}</option>
                            {/if}
                        {/foreach}
                    {/if}
                </select>
                {if isset($errors["parentId"])}
                <label class="error">{echo join("<br/>", $errors["parentId"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Rank <small>(1-99)</small></label>
            <span class="field">
                <input class="longinput" type="text" pattern="[\d]{0,2}" name="rank" value="{echo $category->rank}" />
                {if isset($errors["rank"])}
                <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active </label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $category->active == 0}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/if}{else}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Pro skupinove </label>
            <span class="field">
                <select class="longinput" name="group">
                    {if $category->isGrouped == 0}
                    <option value="0" selected>no</option>
                    <option value="1">yes</option>
                    {/if}{else}
                    <option value="0">no</option>
                    <option value="1" selected>yes</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Pro prodejne </label>
            <span class="field">
                <select class="longinput" name="selable">
                    {if $category->isSelable == 0}
                    <option value="0" selected>no</option>
                    <option value="1">yes</option>
                    {/if}{else}
                    <option value="0">no</option>
                    <option value="1" selected>yes</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Je oddelovac </label>
            <span class="field">
                <select class="longinput" name="separator">
                    {if $category->isSeparator == 0}
                    <option value="0" selected>no</option>
                    <option value="1">yes</option>
                    {/if}{else}
                    <option value="0">no</option>
                    <option value="1" selected>yes</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Description</label>
            <span class="field">
                <textarea cols="85" rows="5" name="text" id="ckeditor">{echo $category->mainText}</textarea>
                {if isset($errors["mainText"])}
                <label class="error">{echo join("<br/>", $errors["mainText"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Title</label>
            <span class="field">
                <input class="longinput" type="text" name="metaTitle" value="{echo $category->metaTitle}" />
                {if isset($errors["metaTitle"])}
                <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Keywords</label>
            <span class="field">
                <input class="longinput" type="text" name="metaKeywords" value="{echo $category->metaKeywords}" />
                {if isset($errors["metaKeywords"])}
                <label class="error">{echo join("<br/>", $errors["metaKeywords"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Meta-Description</label>
            <span class="field">
                <textarea cols="85" rows="5" name="metaDescription" id="ckeditor">{echo $category->metaDescription}</textarea>
                {if isset($errors["metaDescription"])}
                <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                {/if}
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditCategory" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>