<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Kategorie</a></li>
    <li><a href="/admin/category/add/">Nová Kategorie</a></li>
</ul><!--maintabmenu-->
<div class="content">
    
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Kategorie</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" action="#" method="post">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                <colgroup>
                    <col class="con0" /> <col class="con1" />
                    <col class="con0" /> <col class="con1" />
                </colgroup>
            <thead>
            <td class="head0">Název</td>
            <td class="head1">Typ</td>
            <td class="head0">Pořadi</td>
            <td class="head1">&nbsp;</td>
            </thead>
            <tbody>
                {if !empty($categories)}
                {foreach $category in $categories}
                <tr>
                    <td>{echo $category->getTitle()}</td>
                    <td>
                        {if $category->isGrouped == 1}
                            Pro skupinove
                        {/if}{elseif $category->isSelable == 1}
                            Pro prodejne
                        {/elseif}{else}
                            Pro bezne
                        {/else}
                    </td>
                    <td>
                        <input type="text" pattern="[\d]{0,2}" name="rank[{echo $category->id}]" value="{echo $category->getRank()}" />
                    </td>
                    <td>
                        <a href="/admin/category/detail/{echo $category->id}" class="btn btn3 btn_info2" title="Podkategorie"></a>
                        <a href="/admin/category/edit/{echo $category->id}" class="btn btn3 btn_pencil" title="Editovat"></a>
                        {if $isAdmin}<a href="/admin/category/delete/{echo $category->id}" class="btn btn3 btn_trash deleteRow" title="Smazat"></a>{/if}
                    </td>
                </tr>
                {/foreach}
                {/if}
            </tbody>
        </table>
        <div class="tableoptions">
            <input class="radius3" type="submit" name="submitSaveCategoryRank" value="Ulozit poradi kategorii"/>
        </div><!--tableoptions-->
    </form>
</div>