<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/news/">Seznam novinek</a></li>
    <li class="current"><a href="#">Nová novinka</a></li>
</ul><!--maintabmenu-->
<div class="content">
    <div class="two_third">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Obsah novinky</span></h2>
            </div><!--contenttitle-->
            <form class="stdform stdform2" method="post" action="#" >
                <input type="hidden" name="tk" id="tk" value="{echo $token}" />
                <p>
                    <label>Název</label>
                    <span class="field">
                        <input class="longinput" type="text" name="title" value="{echo isset($news)? $news->title: ""}" />
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Autor</label>
                    <span class="field">
                        <input type="text" name="author" class="longinput" value="{echo $authUser->getWholeName()}"/>
                    </span>
                </p>
                <p>
                    <label>Text*<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea rows="20" name="text" id="ckeditor">{echo isset($news)? $news->body: ""}</textarea>
                        {if isset($errors["text"])}
                        <label class="error">{echo join("<br/>", $errors["text"])}</label>
                        {/if}
                        <br/>
                        <button id="news-clear-text">Clear</button>
                    </span>
                </p>
                <p class="stdformbutton">
                    <input name="submitAddNews" type="submit" value="Uložit" class="submit radius2" />
                    <input type="reset" class="reset radius2" value="Reset" />
                </p>
            </form>
        </div>
    </div>

    <div class="one_third last">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Foto</span></h2>
            </div><!--contenttitle-->
            <div class="news-photos">
                {if ($photos && !empty($photos))}
                {foreach $photo in $photos}
                <span class="news-photo">
                    <img src="{echo $photo->getImgThumb()}" alt="{echo $photo->getPhotoName()}" width="200px"/>
                    <button class="stdbtn img-to-text" value="{echo $photo->getId()}">Vložit</button>
                </span>
                {/foreach}
                {/if}
            </div>

        </div>
    </div>
</div>
<br class="clear-all"/>
<script type="text/javascript" src="/public/js/custom/news.js"></script>
