<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/news/">Seznam novinek</a></li>
    <li><a href="/admin/news/add/">Nová novinka</a></li>
    <li class="current"><a href="#">Upravit novinku</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="two_third">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Obsah novinky</span></h2>
            </div><!--contenttitle-->

            <form class="stdform stdform2" method="post" action="#" >
                <input type="hidden" name="tk" id="tk" value="{echo $token}" />
                <p>
                    <label>Název</label>
                    <span class="field">
                        <input type="text" name="title" value="{echo $news->title}" />
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Autor</label>
                    <span class="field">
                        <input type="text" name="author" class="longinput" value="{echo $authUser->getWholeName()}"/>
                    </span>
                </p>
               

                <p>
                    <label>Text*<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea rows="20" name="text" id="ckeditor">{echo $news->body}</textarea>
                        {if isset($errors["text"])}
                        <label class="error">{echo join("<br/>", $errors["text"])}</label>
                        {/if}
                        <br/>
                        <button id="news-clear-text">Clear</button>
                    </span>
                </p>

                <p>
                    <label>Aktivní</label>
                    <span class="field">
                        <select name="active" class="longinput">
                            {if $news->active}
                            <option value="0">Inactive</option>
                            <option value="1" selected>Active</option>
                            {/if}
                            {else}
                            <option value="0" selected>Inactive</option>
                            <option value="1">Active</option>
                            {/else}
                        </select>
                    </span>
                </p>

                <p class="stdformbutton">
                    <input name="submitEditNews" type="submit" value="Save" class="submit radius2" />
                    <input type="reset" class="reset radius2" value="Reset" />
                </p>
            </form>
        </div>
    </div><div class="one_third last">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Photos</span></h2>
            </div><!--contenttitle-->
            <div class="news-photos">
                {if ($photos && !empty($photos))}
                {foreach $photo in $photos}
                <span class="news-photo">
                    <img src="{echo $photo->getImgThumb()}" alt="{echo $photo->getPhotoName()}" width="200px"/>
                    <button class="stdbtn img-to-text" value="{echo $photo->getId()}">Přidat</button>
                </span>
                {/foreach}
                {/if}
            </div>

        </div>
    </div>
    <br clear="all"/>
</div>
<br clear="all"/>
<script type="text/javascript" src="/public/js/custom/news.js"></script>

