<article class="grid_12">
    <h1 class="left">News</h1>
    <a class="button-orange right" href="/admin/news/add/">+ Add News</a>
    <div class="clear"></div><br/><br/>

    {if !empty($news)}       
        <table class="stdtable">
            <thead>
                <th>Title</th>
                <th>Url Key</th>
                <th>Author</th>
                <th>Active</th>
                <th>Created</th>
                <th>Manage</th>
            </thead>
            <tbody>
                {foreach $new in $news}
                    <tr>
                        <td>{echo $new->getTitle()}</td>
                        <td>{echo $_news->getUrlKey()}</td>
                        <td>{echo $new->getAuthor()}</td>
                        <td>{echo $new->getActive()}</td>
                        <td>{echo $new->getCreated()}</td>
                        <td>
                            <a class="button-edit" href="/admin/news/edit/{echo $new->id}" >Edit</a>
                            {if $isAdmin}<a class="button-delete" href="/admin/news/delete/{echo $new->id}" >Delete</a>{/if}
                        </td>

                    </tr>
                {/foreach}
            </tbody>
        </table>
    {/if}
</article>
