<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/product/">Product List</a></li>
    <li class="current"><a href="#">Add new product</a></li>
</ul>
<div class="content">

    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>New Product</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2 uploadPhotoForm" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>
        <div id="tabs">
            <ul class="maintabmenu multipletabmenu">
                <li><a href="#basic">Basic Information</a></li>
                <li><a href="#additional">Additional Information</a></li>
                <li><a href="#meta">Meta Information</a></li>
                <li><a href="#recommended">Recommended products</a></li>
                <li><a href="#photos">Additional photos</a></li>
            </ul>

            <div id="basic">
                <p>
                    <label>Title*</label>
                    <span class="field" >
                        <input required class="longinput" type="text" name="title" 
                               value="{echo isset($product)? $product->title: ""}" />
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Product Code*</label>
                    <span class="field">
                        <input required class="longinput" type="text" name="productcode" 
                               value="{echo isset($product)? $product->productCode: ""}" />
                        {if isset($errors["productCode"])}
                        <label class="error">{echo join("<br/>", $errors["productCode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Product Type*</label>
                    <span class="field">
                        <select name="producttype" class="longinput product-select">
                            <option value="1">Product bez variant</option>
                            <option value="2">Product s variantami</option>
                        </select>
                        {if isset($errors["productType"])}
                        <label class="error">{echo join("<br/>", $errors["productType"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Description*<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea required rows="20" name="description" id="ckeditor">{echo isset($product)? $product->description: ""}</textarea>
                        {if isset($errors["description"])}
                        <label class="error">{echo join("<br/>", $errors["description"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Main Image*</label>
                    <span class="field">
                        <input type="file" name="mainfile"/>
                        {if isset($errors["mainfile"])}
                        <label class="error">
                            {echo join("<br/>", $errors["mainfile"])}
                        </label>
                        {/if}
                    </span> 

                </p>
                <p>
                    <label>Size*</label>
                    <span class="field select-size">
                        <select required class="longinput" name="size">
                            {if !empty($sizes)}
                            {foreach $size in $sizes}
                            <option value="{echo $size->id}">{echo $size->title}</option>
                            {/foreach}
                            {/if}
                        </select>
                        {if isset($errors["sizeId"])}
                        <label class="error">{echo join("<br/>", $errors["sizeId"])}</label>
                        {/if}
                    </span>
                    <span class="field check-size nodisplay">
                        {if !empty($sizes)}
                            {foreach $size in $sizes}
                            <input type="checkbox" name="size[]" value="{echo $size->id}">{echo $size->title}<br/>
                            {/foreach}
                        {/if}
                        {if isset($errors["sizeId"])}
                        <label class="error">{echo join("<br/>", $errors["sizeId"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Current price*</label>
                    <span class="field">
                        <input required class="longinput" type="text" title="numbers only" pattern="[\d]*[\.,]?[\d]+"  name="currentprice" 
                               value="{echo isset($product)? $product->currentPrice: ""}" />
                        {if isset($errors["currentPrice"])}
                        <label class="error">{echo join("<br/>", $errors["currentPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <div class="par">
                    <label>Category*</label>
                    <div class="field">
                        {if isset($categories)}
                            {macro showSubs($catSubs)}
                            <ul>
                                {foreach $sub in $catSubs}
                                <li><input type="checkbox" name="rcat[]" value="{echo $sub->id}" /><span>{echo $sub->title}</span>
                                    {if $sub->subcategory !== null}
                                        {echo showSubs($sub->subcategory)}
                                    {/if}
                                </li>
                                {/foreach}
                            </ul>
                            {/macro}

                            <ul class="category-tree">
                                {foreach $cat in $categories}
                                <li>
                                    <input type="checkbox" name="rcat[]" value="{echo $cat->id}" /><span>{echo $cat->title}</span>
                                    {if $cat->subcategory !== null}
                                    {echo showSubs($cat->subcategory)}
                                    {/if}
                                </li>
                                {/foreach}
                            </ul>
                        {/if}
                        {if isset($errors["category"])}
                        <label class="error">{echo join("<br/>", $errors["category"])}</label>
                        {/if}
                    </div>
                </div>
            </div>

            <div id="additional">
                 <p>
                    <label>Basic price</label>
                    <span class="field">
                        <input class="longinput" type="text" title="numbers only" pattern="[\d]*[\.,]?[\d]+" name="basicprice" 
                               value="{echo isset($product)? $product->basicPrice: ""}" />
                        {if isset($errors["basicPrice"])}
                        <label class="error">{echo join("<br/>", $errors["basicPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Regular price</label>
                    <span class="field">
                        <input class="longinput" type="text" title="numbers only" pattern="[\d]*[\.,]?[\d]+"  name="regularprice" 
                               value="{echo isset($product)? $product->regularPrice: ""}" />
                        {if isset($errors["regularPrice"])}
                        <label class="error">{echo join("<br/>", $errors["regularPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Discount</label>
                    <span class="field">
                        <input class="longinput" type="text" title="numbers only" pattern="[\d]*[\.,]?[\d]+"  name="discount" 
                               value="{echo isset($product)? $product->discount: ""}" />
                        {if isset($errors["discount"])}
                        <label class="error">{echo join("<br/>", $errors["discount"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Discount start</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="discountfrom" 
                               value="{echo isset($product)? $product->discountFrom: ""}" />
                        {if isset($errors["discountFrom"])}
                        <label class="error">{echo join("<br/>", $errors["discountFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Discount end</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="discountto" 
                               value="{echo isset($product)? $product->discountTo: ""}" />
                        {if isset($errors["discountTo"])}
                        <label class="error">{echo join("<br/>", $errors["discountTo"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>EAN</label>
                    <span class="field" >
                        <input class="longinput" type="text" title="numbers only" pattern="[\d]*[\.,]?[\d]+" name="eancode" 
                               value="{echo isset($product)? $product->eanCode: ""}" />
                        {if isset($errors["eanCode"])}
                        <label class="error">{echo join("<br/>", $errors["eanCode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Weight</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="weight" 
                               value="{echo isset($product)? $product->weight: ""}" />
                        {if isset($errors["weight"])}
                        <label class="error">{echo join("<br/>", $errors["weight"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>in action </label>
                    <span class="field">
                        <select class="longinput" name="inaction">
                            <option value="0" selected>No</option>
                            <option value="1">Yes</option>
                        </select>
                    </span>
                </p>
                <p>
                    <label>New start</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="newfrom" 
                               value="{echo isset($product)? $product->newFrom: ""}" />
                        {if isset($errors["newFrom"])}
                        <label class="error">{echo join("<br/>", $errors["newFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>New end</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="newto" 
                               value="{echo isset($product)? $product->newTo: ""}" />
                        {if isset($errors["newTo"])}
                        <label class="error">{echo join("<br/>", $errors["newTo"])}</label>
                        {/if}
                    </span>
                </p>
                
            </div>
            
            <div id="meta">
                <p>
                    <label>Meta-Title</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metatitle" 
                               value="{echo isset($product)? $product->metaTitle: ""}" />
                        {if isset($errors["metaTitle"])}
                        <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Keywords</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metakeywords" 
                               value="{echo isset($product)? $product->metaKeaywords: ""}" />
                        {if isset($errors["metaKeaywords"])}
                        <label class="error">{echo join("<br/>", $errors["metaKeaywords"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Description<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea rows="20" name="metadescription" id="ckeditor" class="longinput">{echo isset($product)? $product->metaDescription: ""}</textarea>
                        {if isset($errors["metaDescription"])}
                        <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                        {/if}
                    </span>
                </p>                                   
            </div>
            
            <div id="recommended">
               <div class="contenttitle radiusbottom0">
                    <h2 class="table"><span>Recommended products</span></h2>
                </div><!--contenttitle-->
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /> <col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0"><input type="checkbox" class="checkall" /></th>
                            <th class="head1">Title</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($allproducts)}
                            {foreach $reproduct in $allproducts}
                                <tr>
                                    <td class="center">
                                        <input type="checkbox" name="recomproductids[]" value="{echo $reproduct->getId()}" />
                                    </td>
                                    <td>{echo $reproduct->getTitle()}</td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>

            <div id="photos">
                <p>
                    <label>Upload more photos</label>
                    <span class="field">
                        <select class="longinput" name="uplMoreImages">
                            <option value="0">No</option>
                            <option value="1">Ano</option>
                        </select>
                    </span>
                </p>
                <p>
                    <label>Image</label>
                    <span class="field">
                        <a href="#" class="btn btn_folder multi_upload"><span>+</span></a>
                        <a href="#" class="btn btn_folder multi_upload_dec"><span>-</span></a>
                    </span>
                    <span class="field file_inputs">
                        <input type="file" name="secondfile[]"/>
                    </span> 
                    <span class="field">
                        {if isset($errors["photom"])}
                        <label class="error">
                            {echo join("<br/>", $errors["photom"])}
                        </label>
                        {/if}
                    </span>
                </p>
            </div>
        </div>
        
        <p class="stdformbutton">
            <input name="submitAddProduct" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>