<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/product/">Produkty</a></li>
    <li class="current"><a href="#">Nový produkt</a></li>
</ul>

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Nový produkt</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2 uploadPhotoForm" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>
        
        <div id="tabs">
            <ul class="maintabmenu multipletabmenu">
                <li><a href="#basic">Základní informace</a></li>
                <li><a href="#additional">Dodatečné informace</a></li>
                <li><a href="#meta">Meta informace</a></li>
                <li><a href="#photos">Dodatečné fotografie</a></li>
            </ul>

            <div id="basic">
                <p>
                    <label>Název*</label>
                    <span class="field" >
                        <input required class="longinput" type="text" name="title" 
                               value="{echo isset($product)? $product->title: ""}" />
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Kód produktu*</label>
                    <span class="field">
                        <input required class="longinput" type="text" name="productcode" 
                               value="{echo isset($product)? $product->productCode: ""}" />
                        {if isset($errors["productCode"])}
                        <label class="error">{echo join("<br/>", $errors["productCode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Typ produktu*</label>
                    <span class="field">
                        <select name="producttype" class="longinput product-select">
                            <option value="bez variant">Kostým bez variant</option>
                            <option value="s variantami">Kostým s variantami</option>
                        </select>
                        {if isset($errors["productType"])}
                        <label class="error">{echo join("<br/>", $errors["productType"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Popis*<small>Max. 30 000 znaků</small></label>
                    <span class="field">
                        <textarea required class="longinput" name="description" id="ckeditor">{echo isset($product)? $product->description: ""}</textarea>
                        {if isset($errors["description"])}
                        <label class="error">{echo join("<br/>", $errors["description"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Hlavní foto*<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
                    <span class="field">
                        <input type="file" name="mainfile"/>
                        {if isset($errors["mainfile"])}
                        <label class="error">{echo join("<br/>", $errors["mainfile"])}</label>
                        {/if}
                        {if isset($errors["imgMain"])}
                        <label class="error">{echo join("<br/>", $errors["imgMain"])}</label>
                        {/if}
                    </span> 
                </p>
                <p>
                    <label>Typ fotografie*</label>
                    <span class="field">
                        <select name="photoType" class="longinput">
                            <option value="0">Portrét</option>
                            <option value="1">Skupinová</option>
                        </select>
                        {if isset($errors["hasGroupPhoto"])}
                        <label class="error">{echo join("<br/>", $errors["hasGroupPhoto"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Velikost*</label>
                    <span class="field select-size">
                        <select required class="longinput" name="size">
                            {if !empty($sizes)}
                            {foreach $size in $sizes}
                            <option value="{echo $size->id}">{echo $size->title}</option>
                            {/foreach}
                            {/if}
                        </select>
                        {if isset($errors["sizeId"])}
                        <label class="error">{echo join("<br/>", $errors["sizeId"])}</label>
                        {/if}
                    </span>
                    <span class="field check-size nodisplay">
                        {if !empty($sizes)}
                            {foreach $size in $sizes}
                                <input type="checkbox" name="size[{echo $size->id}]" value="{echo $size->id}">{echo $size->title}<br/>
                            {/foreach}
                        {/if}
                        {if isset($errors["sizeId"])}
                        <label class="error">{echo join("<br/>", $errors["sizeId"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Základní cena*</label>
                    <span class="field">
                        <input required class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="basicprice" 
                               value="{echo isset($product)? $product->basicPrice: ""}" />
                        {if isset($errors["basicPrice"])}
                        <label class="error">{echo join("<br/>", $errors["basicPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Víkendová cena <small>Výchozí: Základní cena + 140</small></label>
                    <span class="field">
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="weekendprice" 
                               value="{echo isset($product)? $product->weekendPrice: ""}" />
                        {if isset($errors["weekendPrice"])}
                        <label class="error">{echo join("<br/>", $errors["weekendPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <div class="par">
                    <label>Kategorie*</label>
                    <div class="field">
                        {if isset($categories)}
                            {macro showSubs($catSubs)}
                            <ul>
                                {foreach $sub in $catSubs}
                                <li><input type="checkbox" name="rcat[]" value="{echo $sub->id}" /><span>{echo $sub->title}</span>
                                    {if $sub->subcategory !== null}
                                        {echo showSubs($sub->subcategory)}
                                    {/if}
                                </li>
                                {/foreach}
                            </ul>
                            {/macro}

                            <ul class="category-tree">
                                {foreach $cat in $categories}
                                <li>
                                    <input type="checkbox" name="rcat[]" value="{echo $cat->id}" /><span>{echo $cat->title}</span>
                                    {if $cat->subcategory !== null}
                                    {echo showSubs($cat->subcategory)}
                                    {/if}
                                </li>
                                {/foreach}
                            </ul>
                        {/if}
                        {if isset($errors["category"])}
                        <label class="error">{echo join("<br/>", $errors["category"])}</label>
                        {/if}
                    </div>
                </div>
            </div>

            <div id="additional">
                <p>
                    <label>Obvyklá cena</label>
                    <span class="field">
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="regularprice" 
                               value="{echo isset($product)? $product->regularPrice: ""}" />
                        {if isset($errors["regularPrice"])}
                        <label class="error">{echo join("<br/>", $errors["regularPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva<small>Procentuálě</small></label>
                    <span class="field">
                        <input class="longinput" type="number" min="0" max="100" title="Pouze čísla 0-100" name="discount" 
                               value="{echo isset($product)? $product->discount: ""}" />
                        {if isset($errors["discount"])}
                        <label class="error">{echo join("<br/>", $errors["discount"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva od</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text" name="discountfrom" 
                               value="{echo isset($product)? $product->discountFrom: ""}" />
                        {if isset($errors["discountFrom"])}
                        <label class="error">{echo join("<br/>", $errors["discountFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva do</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text" name="discountto" 
                               value="{echo isset($product)? $product->discountTo: ""}" />
                        {if isset($errors["discountTo"])}
                        <label class="error">{echo join("<br/>", $errors["discountTo"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>EAN</label>
                    <span class="field" >
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="eancode" 
                               value="{echo isset($product)? $product->eanCode: ""}" />
                        {if isset($errors["eanCode"])}
                        <label class="error">{echo join("<br/>", $errors["eanCode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Hmotnost</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="weight" 
                               value="{echo isset($product)? $product->weight: ""}" />
                        {if isset($errors["weight"])}
                        <label class="error">{echo join("<br/>", $errors["weight"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>V akci</label>
                    <span class="field">
                        <select class="longinput" name="inaction">
                            <option value="0">Ne</option>
                            <option value="1">Ano</option>
                        </select>
                    </span>
                </p>
                <p>
                    <label>Novinka od</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text" name="newfrom" 
                               value="{echo isset($product)? $product->newFrom: ""}" />
                        {if isset($errors["newFrom"])}
                        <label class="error">{echo join("<br/>", $errors["newFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Novinka do</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text" name="newto" 
                               value="{echo isset($product)? $product->newTo: ""}" />
                        {if isset($errors["newTo"])}
                        <label class="error">{echo join("<br/>", $errors["newTo"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Overlay</label>
                    <span class="field">
                        <input class="longinput" type="text" name="overlay" 
                               value="{echo isset($product)? $product->overlay: ""}" />
                        {if isset($errors["overlay"])}
                        <label class="error">{echo join("<br/>", $errors["overlay"])}</label>
                        {/if}
                    </span>
                </p>
            </div>
            
            <div id="meta">
                <p>
                    <label>Meta-Název</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metatitle" 
                               value="{echo isset($product)? $product->metaTitle: ""}" />
                        {if isset($errors["metaTitle"])}
                        <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Klíčová slova</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metakeywords" 
                               value="{echo isset($product)? $product->metaKeywords: ""}" />
                        {if isset($errors["metaKeaywords"])}
                        <label class="error">{echo join("<br/>", $errors["metaKeaywords"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Popis<small>Max. 5000 znaků</small></label>
                    <span class="field">
                        <textarea name="metadescription" class="longinput">{echo isset($product)? $product->metaDescription: ""}</textarea>
                        {if isset($errors["metaDescription"])}
                        <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                        {/if}
                    </span>
                </p>
            </div>

            <div id="photos">
                <p>
                    <label>Nahrát více fotek</label>
                    <span class="field">
                        <select class="longinput" name="uplMoreImages">
                            <option value="0">Ne</option>
                            <option value="1">Ano</option>
                        </select>
                    </span>
                </p>
                <p>
                    <label>Foto<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
                    <span class="field">
                        <a href="#" class="btn btn_folder multi_upload" title="Pridat pole pro fotografii"><span>+</span></a>
                        <a href="#" class="btn btn_folder multi_upload_dec" title="Odebrat pole pro fotografii"><span>-</span></a>
                    </span>
                    <span class="field file_inputs">
                        <input type="file" name="secondfile[]"/>
                    </span> 
                    <span class="field">
                        {if isset($errors["photom"])}
                        <label class="error">
                            {echo join("<br/>", $errors["photom"])}
                        </label>
                        {/if}
                    </span>
                </p>
            </div>
        </div>
        
        <p class="stdformbutton">
            <input name="submitAddProduct" type="submit" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>