<div class="content">
    <form class="stdform stdform2" method="post" action="/admin/product/addrecommended/{echo $productid}">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <p>
            <label>ID produktu</label>
            <span class="field" >
                <input class="longinput" type="text" name="recomproductid" />
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitSaveRecommended" type="submit" value="Uložit" class="submit radius2" />
        </p>
    </form>
</div>