<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/product/">Produkty</a></li>
    <li><a href="/admin/product/add/">Nový produkt</a></li>
    <li class="current"><a href="#">Editovat produkt</a></li>
</ul>

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Editovat produkt</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2 uploadPhotoForm" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>

        <div id="tabs">
            <ul class="maintabmenu multipletabmenu">
                <li><a href="#basic">Základní informace</a></li>
                <li><a href="#additional">Doplňující informace</a></li>
                <li><a href="#meta">Meta informace</a></li>
                <li><a href="#recommended">Doporučené produkty</a></li>
                <li><a href="#photos">Doplňující fotografie</a></li>
                <li><a href="#variants">Varianty</a></li>
            </ul>

            <div id="basic">
                <p>
                    <label>Název*</label>
                    <span class="field" >
                        <input required class="longinput" type="text" name="title" 
                               value="{echo $product->title}" />
                        {if isset($errors["title"])}
                        <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Kód produktu*</label>
                    <span class="field">
                        <input required class="longinput" type="text" name="productcode" 
                               value="{echo $product->productCode}" />
                        {if isset($errors["productcode"])}
                        <label class="error">{echo join("<br/>", $errors["productcode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Popis*<small>Max. 5000 znaků</small></label>
                    <span class="field">
                        <textarea required class="longinput" name="description" id="ckeditor">{echo $product->description}</textarea>
                        {if isset($errors["description"])}
                        <label class="error">{echo join("<br/>", $errors["description"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Hlavní obrázek*</label>
                    {if $product->imgMain != ""}
                    <span class="field" id="currentLogo">
                        <img src="{echo $product->imgThumb}" alt="" height="100px" />
                        <a href="#" value="{echo $product->id}" id="delImg" class="btn btn3 btn_trash" title="Smazat"></a>
                    </span> 

                    <span class="field nodisplay" id="uploadLogo" >
                        <input type="file" name="mainfile" />
                        {if isset($errors["mainfile"])}
                        <label class="error">{echo join("<br/>", $errors["mainfile"])}</label>
                        {/if}
                    </span>
                    {/if}{else}
                    <span class="field" id="uploadLogo">
                        <input type="file" name="mainfile" />
                        {if isset($errors["mainfile"])}
                        <label class="error">{echo join("<br/>", $errors["mainfile"])}</label>
                        {/if}
                    </span> 
                    {/else}
                </p>
                <p>
                    <label>Velikost*</label>
                    <span class="field">
                        <select required class="longinput" name="size">
                            {if !empty($sizes)}
                            {foreach $size in $sizes}
                            {script $s = ""}
                            {if $product->sizeId == $size->id}
                            {script $s = "selected"}
                            {/if}
                            <option value="{echo $size->id}" {echo $s}>{echo $size->title}</option>
                            {/foreach}
                            {/if}
                        </select>
                        {if isset($errors["size"])}
                        <label class="error">{echo join("<br/>", $errors["size"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Aktuální cena*</label>
                    <span class="field">
                        <input required class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+"  name="currentprice" 
                               value="{echo $product->currentPrice}" />
                        {if isset($errors["currentPrice"])}
                        <label class="error">{echo join("<br/>", $errors["currentPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <div class="par">
                    <label>Kategorie*</label>
                    <div class="field">
                        {if isset($categories)}
                        {macro showSubs($catSubs, $usedCat)}
                        <ul>
                            {foreach $sub in $catSubs}
                            {script $ch = ""}
                            {if in_array($sub->getId(), $usedCat)}
                            {script $ch = "checked=\"checked\""}
                            {/if}
                            <li>
                                <input type="checkbox" name="rcat[]" value="{echo $sub->id}" {echo $ch}/><span>{echo $sub->title}</span>
                                {if $sub->subcategory !== null}
                                {echo showSubs($sub->subcategory, $usedCat)}
                                {/if}
                            </li>
                            {/foreach}
                        </ul>
                        {/macro}

                        <ul class="category-tree">
                            {foreach $cat in $categories}
                            <li>
                                {script $ch = ""}
                                {if in_array($cat->getId(), $productcategoryids)}
                                {script $ch = "checked=\"checked\""}
                                {/if}
                                <input type="checkbox" name="rcat[]" value="{echo $cat->id}" {echo $ch} /><span>{echo $cat->title}</span>
                                {if $cat->subcategory !== null}
                                {echo showSubs($cat->subcategory, $productcategoryids)}
                                {/if}
                            </li>
                            {/foreach}
                        </ul>
                        {/if}
                        {if isset($errors["category"])}
                        <label class="error">{echo join("<br/>", $errors["category"])}</label>
                        {/if}
                    </div>
                </div>
                <p>
                    <label>Aktivní</label>
                    <span class="field">
                        <select name="active">
                            {if $product->active}
                            <option value="0">Neaktivní</option>
                            <option value="1" selected>Aktivní</option>
                            {/if}{else}
                            <option value="0" selected>Neaktivní</option>
                            <option value="1">Aktivní</option>
                            {/else}
                        </select>
                    </span>
                </p>
            </div>

            <div id="additional">
                <p>
                    <label>Základní cena</label>
                    <span class="field">
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="basicprice" 
                               value="{echo $product->basicPrice}" />
                        {if isset($errors["basicPrice"])}
                        <label class="error">{echo join("<br/>", $errors["basicPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Obvyklá cena</label>
                    <span class="field">
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+"  name="regularprice" 
                               value="{echo $product->regularPrice}" />
                        {if isset($errors["regularPrice"])}
                        <label class="error">{echo join("<br/>", $errors["regularPrice"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva</label>
                    <span class="field">
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+"  name="discount" 
                               value="{echo $product->discount}" />
                        {if isset($errors["discount"])}
                        <label class="error">{echo join("<br/>", $errors["discount"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva od</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="discountfrom" 
                               value="{echo $product->discountFrom}" />
                        {if isset($errors["discountFrom"])}
                        <label class="error">{echo join("<br/>", $errors["discountFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Sleva do</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="discountto" 
                               value="{echo $product->discountTo}" />
                        {if isset($errors["discountTo"])}
                        <label class="error">{echo join("<br/>", $errors["discountTo"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>EAN</label>
                    <span class="field" >
                        <input class="longinput" type="text" title="Pouze čísla" pattern="[\d]*[\.,]?[\d]+" name="eancode" 
                               value="{echo $product->eanCode}" />
                        {if isset($errors["eanCode"])}
                        <label class="error">{echo join("<br/>", $errors["eanCode"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Hmotnost</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="weight" 
                               value="{echo $product->weight}" />
                        {if isset($errors["weight"])}
                        <label class="error">{echo join("<br/>", $errors["weight"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>V akci</label>
                    <span class="field">
                        <select name="inaction">
                            {if $product->isInAction == 0}
                            <option value="0" selected>Ne</option>
                            <option value="1">Ano</option>
                            {/if}{else}
                            <option value="0">Ne</option>
                            <option value="1" selected>Ano</option>
                            {/else}
                        </select>
                    </span>
                </p>
                <p>
                    <label>Novinka od</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="newfrom" 
                               value="{echo $product->newFrom}" />
                        {if isset($errors["newFrom"])}
                        <label class="error">{echo join("<br/>", $errors["newFrom"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Novinka do</label>
                    <span class="field">
                        <input class="longinput datepicker" type="text"  name="newto" 
                               value="{echo $product->newTo}" />
                        {if isset($errors["newTo"])}
                        <label class="error">{echo join("<br/>", $errors["newTo"])}</label>
                        {/if}
                    </span>
                </p>
            </div>

            <div id="meta">
                <p>
                    <label>Meta-Název</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metatitle" 
                               value="{echo $product->metaTitle}" />
                        {if isset($errors["metaTitle"])}
                        <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Klíčová slova</label>
                    <span class="field" >
                        <input class="longinput" type="text" name="metakeywords" 
                               value="{echo $product->metaKeaywords}" />
                        {if isset($errors["metaKeaywords"])}
                        <label class="error">{echo join("<br/>", $errors["metaKeaywords"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Meta-Popis<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea name="metadescription" class="longinput">{echo $product->metaDescription}</textarea>
                        {if isset($errors["metaDescription"])}
                        <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                        {/if}
                    </span>
                </p>                                   
            </div>

            <div id="recommended">
                <div class="contenttitle radiusbottom0">
                    <h2 class="form"><span>Doporučené produkty</span></h2>
                </div><br/>
                <a class="btn btn_link dialog" href="/admin/product/addrecommended/{echo $product->getId()}"
                   value="Přidat doporučený produkt">
                    <span>Přidat doporučený produkt</span>
                </a><br/>
                
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /> <col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Title</th>
                            <th class="head1">Product code</th>
                            <th class="head0">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($recomproducts)}
                        {foreach $reproduct in $recomproducts}
                        <tr>
                            <td>{echo $reproduct->getTitle()}</td>
                            <td>{echo $reproduct->getProductCode()}</td>
                            <td><a href="/admin/product/deleterecommended/{echo $product->getId()}/{echo $reproduct->getId()}" class="btn btn3 btn_trash deleteRow"></a></td>
                        </tr>
                        {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>

            <div id="photos">
                <p>
                    <label>Nahrát více fotek</label>
                    <span class="field">
                        <select class="longinput" name="uplMoreImages">
                            <option value="0">Ne</option>
                            <option value="1">Ano</option>
                        </select>
                    </span>
                </p>
                <p>
                    <label>Obrázek</label>
                    <span class="field">
                        <a href="#" class="btn btn_folder multi_upload"><span>+</span></a>
                        <a href="#" class="btn btn_folder multi_upload_dec"><span>-</span></a>
                    </span>
                    <span class="field file_inputs">
                        <input type="file" name="secondfile[]"/>
                    </span> 
                    <span class="field">
                        {if isset($errors["photom"])}
                        <label class="error">
                            {echo join("<br/>", $errors["photom"])}
                        </label>
                        {/if}
                    </span>
                </p>
                <div>
                    {script $productphotos = $product->additionalPhotos}
                    {if !empty($productphotos)}
                    <div style="overflow:hidden;">
                        <ul class="imagelist">
                            {foreach $photo in $productphotos}
                            {if $photo->active}
                            <li class="photoactive">
                                {/if} 
                                {else}
                            <li class="photoinactive">
                                {/else}
                                <img src="{echo $photo->imgThumb}" alt="" height="150px" />
                                <span>
                                    <a href="{echo $photo->imgMain}" class="view"></a>
                                    <a href="/admin/product/changephotostatus/{echo $photo->id}" class="activate" value="Změnit status fotky"></a>
                                    <a href="/admin/product/deleteproductphoto/{echo $photo->id}" class="delete" value="Smazat fotku"></a>
                                </span>
                            </li>
                            {/foreach}
                        </ul>
                    </div>
                    {/if} 
                </div>
            </div>

            <div id="variants">
                <div class="contenttitle radiusbottom0">
                    <h2 class="form"><span>Varianty produktu</span></h2>
                </div>
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /> <col class="con1" />
                        <col class="con0" /> <col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Velikost</th>
                            <th class="head0">Kód produktu</th>
                            <th class="head1">Aktuální cena</th>
                            <th class="head0">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $variants = $product->variants}
                        {if !empty($variants)}
                        {foreach $variant in $variants}
                        <tr>
                            <td>{echo $variant->getTitle()}</td>
                            <td>{echo $variant->sizeTitle}</td>
                            <td>{echo $variant->getProductCode()}</td>
                            <td>{echo $variant->getCurrentPrice()}</td>
                            <td>
                                <a href="/admin/product/edit/{echo $variant->id}" class="btn btn3 btn_pencil" title="Editovat"></a>
                                {if $isAdmin}<a href="/admin/product/delete/{echo $variant->id}" class="btn btn3 btn_trash deleteRow" title="Smazat"></a>{/if}
                            </td>
                        </tr>
                        {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
        <p class="stdformbutton">
            <input name="submitEditProduct" type="submit" value="Uložit" class="submit radius2" />
        </p>
    </form>
</div>