<ul>
    
    <li><a {if $active == 1} id="activeLi1" {/if} href="/o-nas"><span>O nás</span></a></li>
    <li><a {if $active == 2} id="activeLi1" {/if} href="/reference"><span>Reference</span></a></li>
    <li><a {if $active == 3} id="activeLi1" {/if} href="/cenik"><span>Ceník</span></a></li>
    <li><a {if $active == 4} id="activeLi1" {/if} href="/kontakty"><span>Kontakty</span></a></li>
    <li><a href="#"><span>Půjčovna</span></a>
        {if isset($activecat)}
        <ul class="dropdownmenu1-display">
        {/if}
        {else}
        <ul class="dropdownmenu1">
        {/else}
            {if !empty($category)}
                {foreach $cat in $category}
                 <li>  
                {if $cat->urlKey == $activecat | isset($parentcat) & $cat->id == $parentcat}
                <a id="activeLi" href="/kategorie/{echo $cat->urlKey}/">    
                {/if}
                    {else}
                        <a href="/kategorie/{echo $cat->urlKey}/">
                    {/else}
                
                    <span>{echo $cat->title}</span></a>


                {script $subcategory = $cat->subcategory}
                {script $count = count($subcategory)}

                {if !empty($subcategory)}
                    {if $count>7}<!--změna pozice dropdown menu při velkém počtu subkategorií-->
                        {if isset($parentcat) & $parentcat == $cat->id | $activecat == "dospele"}
                            <ul class="dropdownmenu3-display">
                        {/if}
                        {else}
                            <ul class="dropdownmenu3">
                        {/else}
                        {foreach $subcat in $subcategory}
                                <li>
                            {if $subcat->urlKey == $activecat}
                                    <a id="activeLi2" href="/kategorie/{echo $subcat->urlKey}/">
                              
                            {/if}
                            {else}
                            <a href="/kategorie/{echo $subcat->urlKey}/">
                            {/else}
                    
                                    <span>{echo $subcat->title}</span></a>
                                </li>
                        {/foreach}
                            </ul>
                    {/if}
                    {else}
                        {if isset($parentcat) & $parentcat == $cat->id | $activecat == "prodej"}
                            <ul class="dropdownmenu2-display">
                        {/if}
                        {else}
                            <ul class="dropdownmenu2">
                        {/else}
                        {foreach $subcat in $subcategory}
                                <li>
                            {if $subcat->urlKey == $activecat}
                                <a id="activeLi2" href="/kategorie/{echo $subcat->urlKey}/">
                            {/if}
                            {else}
                                <a href="/kategorie/{echo $subcat->urlKey}/">
                            {/else}
                                <span>{echo $subcat->title}</span></a>
                            </li>
                        {/foreach}
                            </ul>
                    {/else}
                {/if}
            </li>
            {/foreach}
                {/if}
        </ul>
    </li>
</ul>