<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/gallery/">Gallery List</a></li>
    <li class="current"><a href="#">Add Gallery</a></li>
</ul><!--maintabmenu-->
<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Add Gallery</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" value="{echo isset($gallery)? $gallery->title: ""}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Description<small>Max. 5000 characters</small></label>
            <span class="field">
                <textarea rows="20" name="description" id="ckeditor">{echo isset($gallery)? $gallery->description: ""}</textarea>
                {if isset($errors["description"])}
                <label class="error">{echo join("<br/>", $errors["description"])}</label>
                {/if}
                <br/>
                <button id="news-clear-text">Clear</button>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitAddGallery" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
