<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Gallery List</a></li>
    <li><a href="/admin/gallery/add/">Add Gallery</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Gallery List</span></h2>
    </div><!--contenttitle-->

    <table class="stdtable">
        <thead>
        <th>Title</th>
        <th>Active</th>
        <th>Created</th>
        <th>Manage</th>
        </thead>
        <tbody>
            {if !empty($collections)}
            {foreach $col in $collections}
            <tr>
                <td>{echo $col->getTitle()}</td>
                <td>{echo $col->getActive()}</td>
                <td>{echo $col->getCreated()}</td>
                <td>
                    <a class="btn btn_image2" class="button-edit" href="/admin/gallery/detail/{echo $col->id}" >
                        Enter gallery
                    </a>
                </td>
            </tr>
            {/foreach}
            {/if}
        </tbody>

    </table>

</div>