{if !empty($products)}
    {foreach $product in $products}
        {if $product->hasGroupPhoto}
            <div class="transparentCategory productCategoryGrouped">
                <a href="/kostym/{echo $product->urlKey}/" >
                    <span>{echo $product->title}</span><br/>
                    <span><img class="grouped" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                    <span class="price">{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                </a>
            </div>
        {/if}
        {else}
            <div class="transparentCategory productCategory">
                <a href="/kostym/{echo $product->urlKey}/" >
                    <span>{echo $product->title}</span><br/>
                    <span><img class="single" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                    <span class="priceSingle">{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                </a>
            </div>
        {/else}
    {/foreach}
{/if}