{if !empty($products)}
    {foreach $product in $products}
        {if $product->hasGroupPhoto}
            <div class="transparentCategory productCategoryGrouped">
                <a href="/kostym/{echo $product->urlKey}/" >
                    <span>{echo $product->title}</span><br/>
                    <span><img class="grouped" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>

                    {if $product->overlay != ""}
                        <div class="rezerve">
                            <p class="rezerveP">{echo $product->overlay}</p>
                        </div>
                    {/if}
                </a>
            </div>
        {/if}
        {else}
            <div class="transparentCategory productCategory">
                <a href="/kostym/{echo $product->urlKey}/" >
                    <span>{echo $product->title}</span><br/>
                    <span><img class="single" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>

                    {if $product->overlay != ""}
                        <div class="rezerve">
                            <p class="rezerveP">{echo $product->overlay}</p>
                        </div>
                    {/if}
                    
                    {if !$category->isGrouped}
                        <span class="priceSingle">
                            {if $category->isSelable}Cena{/if}{else}Za 1. den{/else} {echo $product->currentPrice}Kč
                        </span>
                    {/if}
                </a>
            </div>
        {/else}
    {/foreach}
{/if}