<script type="text/javascript" src="/public/js/custom/dashboard.js"></script>
<ul class="maintabmenu">
    <li class="current"><a href="/admin/">Dashboard</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="one_half">
        <div class="contenttitle">
            <h2 class="button"><span>Přidat</span></h2>
        </div><!--contenttitle-->
        <ul class="widgetlist">
            <li><a href="/admin/news/add/" class="message">Aktualitu</a></li>
            <li><a href="/admin/reference/add/" class="message">Referenci</a></li>
            <li><a href="/admin/product/add/" class="upload">Produkt</a></li>
            <li><a href="/admin/category/" class="events">Kategorii</a></li>
        </ul>
    </div>

    <br clear="all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Poslední aktuality</span></h2></div>
            <div class="widgetcontent announcement">
                {if !empty($latestnews)}
                    {foreach $news in $latestnews}
                        <p>
                            <span class="radius2">Title: {echo $news->getTitle()}</span>
                            <span class="radius2">Created: {echo $news->getCreated()}</span>
                            <br/><br/>
                            {echo $news->shortBody}
                        </p>
                        <hr/>
                    {/foreach}
                {/if}
                {else}
                <p>No news</p>
                {/else}
            </div><!--widgetcontent-->
        </div><!--widgetbox-->

    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější reference</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" />
                        <col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Autor</th>
                            <th class="head0">Vytvořeno</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestrefs)}
                            {foreach $ref in $latestrefs}
                                <tr>
                                    <td>{echo $ref->getTitle()}</td>
                                    <td>{echo $ref->getAuthor()}</td>
                                    <td>{echo $ref->getCreated()}</td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <br class="clear-all"/><br />

    <div class="two_third">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější produkty</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Foto</th>
                            <th class="head1">Název</th>
                            <th class="head0">Kód produktu</th>
                            <th class="head1">Aktuální cena</th>
                            <th class="head0">Vytovřeno</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestproducts)}
                            {foreach $product in $latestproducts}
                                <tr>
                                    <td><img src="{echo $product->getImgThumb()}" alt="" height="80" /></td>
                                    <td><a href="/admin/product/edit/{echo $product->getId()}">{echo $product->getTitle()}</a></td>
                                    <td>{echo $product->getProductCode()}</td>
                                    <td>{echo $product->getCurrentPrice()}</td>
                                    <td>{echo $product->getCreated()}</td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox--> 
    </div><!--one_half-->
    <br class="clear-all"/><br />
</div><!--content-->