<article >
    <h1 class="visuallyhidden">Kategorie</h1>
    <div class="categoryRadit transparentCategory">
        <table>
            <tr>
                <td>Řadit dle</td>
                <td>
                    <select id="catvieworderby" name="catvieworderby">
                        
                        <option value="created" {if $catorderby == "created"}selected{/if}>Nejnovější</option>
                        <option value="currentPrice" {if $catorderby == "currentPrice"}selected{/if}>Ceny</option>
                        <option value="title" {if $catorderby == "title"}selected{/if}>Jména</option>
                    </select>
                </td></tr>
            <tr><td></td>
                <td>
                    <select id="catvieworder" name="catvieworder">
                        <option value="asc" {if $catorder == "asc"}selected{/if}>Vzestupně</option>
                        <option value="desc" {if $catorder == "desc"}selected{/if}>Sestupně</option>
                    </select>
                </td>
            </tr>
               
        </table>
    </div>
    <div class="category">
         
    {if !empty($products)}
        {foreach $product in $products}
            {if $product->hasGroupPhoto}
                <div class="transparentCategory productCategoryGrouped">
                    <a href="/kostym/{echo $product->urlKey}/" >
                        <span>{echo $product->title}</span><br/>
                        <span><img class="grouped" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                        <span class="price">{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                    </a>
                </div>
            {/if}
            {else}
                 <div class="transparentCategory productCategory">
                    <a href="/kostym/{echo $product->urlKey}/" >
                        <span>{echo $product->title}</span><br/>
                        <span><img class="single" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                        <span class="priceSingle">{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                    </a>
                </div>
            {/else}
        {/foreach}
    {/if}
    {else}
        <div class="errorDiv transparentCategory">
            <span>V této kategorii nejsou, žádné kostýmy</span>    
        </div>
    {/else} 
    </div>
  
</article>

