{if !empty($categories)}
    <article class="searchCategory transparentAbout">
        <h1 class="visuallyhidden">Search content</h1>
        <span>Výraz <i>{echo $query}</i> byl nalezen v těchto kategoriích:</span><br/>
        {foreach $cat in $categories}
        <a class="kategorieButton" href="/kategorie/{echo $cat->urlKey}/">{echo $cat->title}</a>
        {/foreach}
    </article>
{/if}

{if !empty($products)}
    <article class="searchProduct ">
        <h1 class="visuallyhidden">Search content</h1>
        <div>
            <span class="transparentAbout">Výraz <i>{echo $query}</i> byl nalezen v těchto kostýmech:</span>
        </div>
    </article>

    <article class="category">
        <h1 class="visuallyhidden">Category</h1>
        {foreach $product in $products}
            {if $product->hasGroupPhoto}
                <div class="transparentCategory productCategoryGrouped">
                    <a href="/kostym/{echo $product->urlKey}/" >
                        <span>{echo $product->title}</span><br/>
                        <span><img class="grouped" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                        <span>{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                    </a>
                </div>
            {/if}
            {else}
                 <div class="transparentCategory productCategory">
                    <a href="/kostym/{echo $product->urlKey}/" >
                        <span>{echo $product->title}</span><br/>
                        <span><img class="single" src="{echo $product->imgThumb}" alt="{echo $product->title}"></span><br/>
                        <span>{if $category->isSelable}Cena{/if}{else}Cena od{/else} {echo $product->currentPrice}Kč</span>
                    </a>
                </div>
            {/else}
        {/foreach}
    </article>
{/if}{else}
    <div class="errorDiv transparentCategory">
        <span>Nebyly nalezeny žádné kostýmy</span>    
    </div>
{/else}