<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/reference/">Seznam Referencí</a></li>
    <li><a href="/admin/reference/add/">Nová Reference</a></li>
    <li class="current"><a href="#">Upravit Referenci</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Reference</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <p>
            <label>Název</label>
            <span class="field">
                <input type="text" name="title" value="{echo $reference->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Typ*</label>
            <span class="field">
                <select name="corporate" class="longinput">
                    {if $reference->isCorporate == 1}
                    <option value="0">Zákaznická</option>
                    <option value="1" selected>Firemní</option>
                    {/if}
                    {else}
                    <option value="0" selected>Zákaznická</option>
                    <option value="1">Firemní</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Autor</label>
            <span class="field">
                <input type="text" name="author" class="longinput" value="{echo $reference->getAuthor()}"/>
            </span>
        </p>
        <p>
            <label>Text*</label>
            <span class="field">
                <textarea rows="20" name="text" id="ckeditor">{echo $reference->body}</textarea>
                {if isset($errors["text"])}
                <label class="error">{echo join("<br/>", $errors["text"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Foto / Logo*</label>
            {if $reference->imgMain != ""}
            <span class="field" id="currentLogo">
                <img src="{echo $reference->imgThumb}" alt="" height="100" />
                <a href="/admin/reference/deleteMainPhoto/{echo $reference->id}" id="delImg" class="btn btn3 btn_trash" title="Smazat"></a>
            </span> 

            <span class="field nodisplay" id="uploadLogo" >
                <input type="file" name="mainfile" />
                {if isset($errors["mainfile"])}
                <label class="error">{echo join("<br/>", $errors["mainfile"])}</label>
                {/if}
            </span>
            {/if}{else}
            <span class="field" id="uploadLogo">
                <input type="file" name="mainfile" />
                {if isset($errors["mainfile"])}
                <label class="error">{echo join("<br/>", $errors["mainfile"])}</label>
                {/if}
            </span> 
            {/else}
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $reference->active == 1}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditReference" type="submit" value="Uložit" class="submit radius2" />
        </p>
    </form>

</div>

